/** ISO 3166-1 alpha-2 for the names people type into a search box. */
export const COUNTRIES = Object.freeze({
  US: 'United States',
  CA: 'Canada',
  MX: 'Mexico',
  BR: 'Brazil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  GB: 'United Kingdom',
  IE: 'Ireland',
  FR: 'France',
  DE: 'Germany',
  NL: 'Netherlands',
  BE: 'Belgium',
  LU: 'Luxembourg',
  CH: 'Switzerland',
  AT: 'Austria',
  IT: 'Italy',
  ES: 'Spain',
  PT: 'Portugal',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  IS: 'Iceland',
  PL: 'Poland',
  CZ: 'Czechia',
  SK: 'Slovakia',
  HU: 'Hungary',
  RO: 'Romania',
  BG: 'Bulgaria',
  GR: 'Greece',
  HR: 'Croatia',
  SI: 'Slovenia',
  RS: 'Serbia',
  UA: 'Ukraine',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  MD: 'Moldova',
  TR: 'Türkiye',
  IL: 'Israel',
  AE: 'United Arab Emirates',
  SA: 'Saudi Arabia',
  BH: 'Bahrain',
  QA: 'Qatar',
  IN: 'India',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  LK: 'Sri Lanka',
  SG: 'Singapore',
  MY: 'Malaysia',
  ID: 'Indonesia',
  TH: 'Thailand',
  VN: 'Vietnam',
  PH: 'Philippines',
  JP: 'Japan',
  KR: 'South Korea',
  TW: 'Taiwan',
  HK: 'Hong Kong',
  CN: 'China',
  AU: 'Australia',
  NZ: 'New Zealand',
  ZA: 'South Africa',
  NG: 'Nigeria',
  KE: 'Kenya',
  EG: 'Egypt',
  MA: 'Morocco',
  RU: 'Russia',
  KZ: 'Kazakhstan',
  GE: 'Georgia',
  AM: 'Armenia',
  CY: 'Cyprus',
  MT: 'Malta',
  PA: 'Panama',
  CR: 'Costa Rica',
  PE: 'Peru',
  UY: 'Uruguay',
});

const ALIASES = {
  usa: 'US',
  'united states': 'US',
  america: 'US',
  'u.s.': 'US',
  us: 'US',
  uk: 'GB',
  britain: 'GB',
  england: 'GB',
  'great britain': 'GB',
  holland: 'NL',
  deutschland: 'DE',
  'czech republic': 'CZ',
  turkey: 'TR',
  korea: 'KR',
  uae: 'AE',
  dubai: 'AE',
  'hong kong': 'HK',
  'south korea': 'KR',
  'new zealand': 'NZ',
  'south africa': 'ZA',
};

/** Regions a query can name, expanded to country lists. */
export const REGIONS = Object.freeze({
  eu: [
    'AT',
    'BE',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'HU',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MT',
    'NL',
    'PL',
    'PT',
    'RO',
    'SK',
    'SI',
    'ES',
    'SE',
  ],
  europe: [
    'AT',
    'BE',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'HU',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MT',
    'NL',
    'PL',
    'PT',
    'RO',
    'SK',
    'SI',
    'ES',
    'SE',
    'GB',
    'CH',
    'NO',
    'IS',
    'UA',
    'RS',
    'MD',
    'TR',
  ],
  'north america': ['US', 'CA', 'MX'],
  'latin america': ['BR', 'AR', 'CL', 'CO', 'MX', 'PE', 'UY', 'CR', 'PA'],
  latam: ['BR', 'AR', 'CL', 'CO', 'MX', 'PE', 'UY', 'CR', 'PA'],
  asia: [
    'SG',
    'JP',
    'KR',
    'IN',
    'HK',
    'TW',
    'MY',
    'ID',
    'TH',
    'VN',
    'PH',
    'CN',
    'PK',
    'BD',
    'LK',
    'KZ',
  ],
  apac: ['SG', 'JP', 'KR', 'IN', 'HK', 'TW', 'MY', 'ID', 'TH', 'VN', 'PH', 'AU', 'NZ'],
  oceania: ['AU', 'NZ'],
  'middle east': ['AE', 'SA', 'IL', 'BH', 'QA', 'TR'],
  africa: ['ZA', 'NG', 'KE', 'EG', 'MA'],
  nordics: ['SE', 'NO', 'DK', 'FI', 'IS'],
  benelux: ['BE', 'NL', 'LU'],
  dach: ['DE', 'AT', 'CH'],
});

const byName = new Map();
for (const [code, name] of Object.entries(COUNTRIES)) byName.set(name.toLowerCase(), code);
for (const [alias, code] of Object.entries(ALIASES)) byName.set(alias, code);

/** "germany" → ["DE"], "eu" → the member list, "DE" → ["DE"], unknown → null. */
export function countriesFor(text) {
  const t = String(text ?? '')
    .trim()
    .toLowerCase();
  if (!t) return null;
  if (REGIONS[t]) return [...REGIONS[t]];
  if (byName.has(t)) return [byName.get(t)];
  const up = t.toUpperCase();
  if (COUNTRIES[up]) return [up];
  return null;
}

export const countryName = (code) =>
  COUNTRIES[String(code ?? '').toUpperCase()] ?? String(code ?? '');

/** Every name and alias, longest first, so a tokeniser tries "south korea" before "korea". */
export const PLACE_WORDS = [...new Set([...byName.keys(), ...Object.keys(REGIONS)])].sort(
  (a, b) => b.length - a.length,
);
